<?php
/**
 * Auteur: SOBANDITH Jimmy
 * Société: Warmbee (Deliv's SARL)
 * Date: 2015
 * Desc: Template du footer
 */
use Phalcon\Tag as Tag;
?>
<?php
	echo $this->getContent();
?>
			<div class="footer">
				<div class="pull-right">
					<strong><?= $mt['version'] ?></strong> <?= $mt['num_version'] ?>
				</div>
				<div>
					<strong><?= $mt['copyright'] ?></strong> <?= $mt['warmbee_2016'] ?>
				</div>
			</div>
		</div>
	</div>
</body>